# Generated by Django 3.0.6 on 2020-05-28 02:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_auto_20200517_2338'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actor',
            options={'verbose_name': 'Актеры и режиссеры', 'verbose_name_plural': 'Актеры и режиссеры'},
        ),
        migrations.AlterModelOptions(
            name='ratingstar',
            options={'ordering': ['-value'], 'verbose_name': 'Звезда Рейтинга Фильма', 'verbose_name_plural': 'Звезды Рейтинга Фильмов'},
        ),
    ]
